overrides:
  postcss@<8.4.31: '>=8.4.31'
  postcss@<8.5.10: '>=8.5.10'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  serialize-javascript@>=5.0.0 <7.0.5: '>=7.0.5'
  swiper@>=6.5.1 <12.1.2: '>=12.1.2'
  uuid@<11.1.1: '>=11.1.1'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  webpack-dev-server@<=5.2.3: '>=5.2.4'
